import { useEffect, useMemo, useRef, useState } from "react";
import { Building2, Camera, Check, Download, FileText, Image, Search, Upload } from "lucide-react";
import { Modal } from "../../components/ui";
import { useFirmalar } from "../../context/FirmaContext";

const API = ((import.meta.env.VITE_API_URL || "").trim() || "https://api.isgpanel.tr").replace(/\/$/, "").replace(/\/api$/, "");
const up = (v) => String(v || "").toLocaleUpperCase("tr-TR");
const getToken = () => localStorage.getItem("token") || sessionStorage.getItem("token") || "";
const cities = "Adana,Adıyaman,Afyonkarahisar,Ağrı,Amasya,Ankara,Antalya,Artvin,Aydın,Balıkesir,Bilecik,Bingöl,Bitlis,Bolu,Burdur,Bursa,Çanakkale,Çankırı,Çorum,Denizli,Diyarbakır,Edirne,Elazığ,Erzincan,Erzurum,Eskişehir,Gaziantep,Giresun,Gümüşhane,Hakkari,Hatay,Isparta,Mersin,İstanbul,İzmir,Kars,Kastamonu,Kayseri,Kırklareli,Kırşehir,Kocaeli,Konya,Kütahya,Malatya,Manisa,Kahramanmaraş,Mardin,Muğla,Muş,Nevşehir,Niğde,Ordu,Rize,Sakarya,Samsun,Siirt,Sinop,Sivas,Tekirdağ,Tokat,Trabzon,Tunceli,Şanlıurfa,Uşak,Van,Yozgat,Zonguldak,Aksaray,Bayburt,Karaman,Kırıkkale,Batman,Şırnak,Bartın,Ardahan,Iğdır,Yalova,Karabük,Kilis,Osmaniye,Düzce".split(",").map(up).sort((a, b) => a.localeCompare(b, "tr"));
const personalFields = [["dogumYeri", "DOĞUM YERİ", cities], ["dogumTarihi", "DOĞUM TARİHİ", null, "date"], ["cinsiyet", "CİNSİYET", ["KADIN", "ERKEK", "DİĞER"]], ["egitimDurumu", "EĞİTİM DURUMU", ["İLKOKUL", "ORTAOKUL", "LİSE", "YÜKSEKOKUL", "LİSANS", "YÜKSEK LİSANS"]], ["medeniDurum", "MEDENİ DURUM", ["BEKAR", "EVLİ", "BOŞANMIŞ", "DUL"]], ["telefon", "TELEFON", null, "tel"], ["evAdresi", "EV ADRESİ"], ["meslegi", "MESLEĞİ"], ["yaptigiIs", "YAPTIĞI İŞ"], ["calistigiBolum", "ÇALIŞTIĞI BÖLÜM"]];
const nfmFields = [["goz", "GÖZ"], ["kulakBurunBogaz", "KULAK BURUN BOĞAZ"], ["deri", "DERİ"], ["kardiyovaskuler", "KARDİYOVASKÜLER SİSTEM"], ["solunum", "SOLUNUM SİSTEMİ"], ["sindirim", "SİNDİRİM SİSTEMİ"], ["urogenital", "ÜROGENİTAL SİSTEM"], ["kasIskelet", "KAS-İSKELET SİSTEMİ"], ["norolojik", "NÖROLOJİK MUAYENE"], ["psikiyatrik", "PSİKİYATRİK MUAYENE"]];
const healthOptions = { "KAN GRUBU": ["0 RH+", "0 RH-", "A RH+", "A RH-", "B RH+", "B RH-", "AB RH+", "AB RH-"], "KRONİK HASTALIK": ["YOK", "HİPERTANSİYON", "DİYABET", "ASTIM", "KOAH", "KALP HASTALIĞI", "DİĞER"], "DİĞER AŞILAR": ["YOK", "COVID-19", "GRİP", "PNÖMOKOK", "HEPATİT A", "HEPATİT B", "DİĞER"], "GÖRME BOZUKLUĞU": ["YOK", "YAKIN GÖRME", "UZAK GÖRME", "ASTİGMAT", "DİĞER"], "AMELİYAT": ["YOK", "APANDİSİT", "FITIK", "SAFRA KESESİ", "ORTOPEDİK", "DİĞER"], "SİGARA": ["KULLANMIYOR", "1 YILDAN AZ", "1-5 YIL", "6-10 YIL", "11 YIL VE ÜZERİ"], "ALKOL": ["KULLANMIYOR", "NADİREN", "AYDA 1-3", "HAFTADA 1-2", "HAFTADA 3 VE ÜZERİ"] };
const binaryHealth = ["BALGAMLI ÖKSÜRÜK", "NEFES DARLIĞI", "GÖĞÜS AĞRISI", "ÇARPINTI", "SIRT AĞRISI", "İSHAL/KABIZLIK", "EKLEM AĞRISI", "KALP HASTALIĞI", "ŞEKER HASTALIĞI", "BÖBREK RAHATSIZLIĞI", "SARILIK", "MİDE/DUODENUM ÜLSERİ", "İŞİTME KAYBI", "SİNİR SİSTEMİ HASTALIĞI", "DERİ HASTALIĞI", "BESİN ZEHİRLENMESİ", "HASTANEDE YATIŞ", "İŞ KAZASI", "MESLEK HASTALIĞI ŞÜPHESİ", "MALULİYET", "DEVAM EDEN TEDAVİ", "YÜKSEKLİK KORKUSU"];
const opinions = ["ÇALIŞMAYA UYGUNDUR", "GECE ÇALIŞABİLİR", "YÜKSEKTE ÇALIŞABİLİR", "ÇOK TEHLİKELİ İŞLERDE ÇALIŞABİLİR", "KISITLI ÇALIŞMAYA UYGUNDUR", "ÇALIŞMAYA UYGUN DEĞİLDİR"];
const restrictions = ["YÜKSEKTE ÇALIŞMA KISITLAMASI", "GECE ÇALIŞMASI KISITLAMASI", "AĞIR KALDIRMA KISITLAMASI", "TOZLU ORTAM KISITLAMASI", "KİMYASAL MARUZİYET KISITLAMASI"];

function BlueButton({ children, className = "", ...props }) { return <button type="button" className={`rounded bg-[#2563eb] px-3 py-1.5 text-xs font-semibold text-white shadow-sm hover:bg-[#1d4ed8] ${className}`} {...props}>{children}</button>; }
function Field({ label, value, setValue, options, type = "text", disabled = false }) { const numeric = type === "number" || type === "tel"; const max = type === "tel" ? 11 : type === "number" ? 3 : undefined; return <div><label className="block text-xs font-medium text-slate-700">{label}</label>{options ? <select value={up(value)} disabled={disabled} onChange={(e) => setValue(up(e.target.value))} className="mt-1 h-9 w-full rounded border border-slate-200 bg-white px-3 text-sm"><option value="">SEÇİNİZ</option>{options.map((x) => <option key={x} value={up(x)}>{up(x)}</option>)}</select> : <input type={type} inputMode={numeric ? "numeric" : undefined} maxLength={max} value={value || ""} disabled={disabled} onChange={(e) => setValue(numeric ? e.target.value.replace(/\D/g, "").slice(0, max) : type === "date" ? e.target.value : up(e.target.value))} className="mt-1 h-9 w-full rounded border border-slate-200 px-3 text-sm uppercase disabled:bg-slate-100" />}</div>; }
function Status({ ok, onClick, title }) { return <button type="button" title={title} onClick={onClick} className={`mx-auto grid h-6 w-6 place-items-center rounded-full text-white ${ok ? "bg-emerald-600" : "bg-amber-500"}`}>{ok ? <Check className="h-4 w-4" /> : "!"}</button>; }

export default function Ek2SaglikMuayenesi({ mode = "ek2" }) {
  const { selectedFirm } = useFirmalar(); const [people, setPeople] = useState([]); const [query, setQuery] = useState(""); const [modal, setModal] = useState(null); const [draft, setDraft] = useState({}); const [saving, setSaving] = useState(false); const canvas = useRef(null); const drawing = useRef(false); const tetkikler = mode === "tetkikler"; const firmId = selectedFirm?.id || selectedFirm?._id;
  const api = async (path, options = {}) => { const response = await fetch(`${API}/api/hekim/ek2${path}`, { ...options, headers: { Authorization: `Bearer ${getToken()}`, "Content-Type": "application/json" } }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).message || "İşlem tamamlanamadı."); return response.json(); };
  const load = async () => { if (!firmId) return setPeople([]); try { setPeople((await api(`/firms/${firmId}`)).persons || []); } catch { setPeople([]); } };
  useEffect(() => { load(); }, [firmId]);
  const rows = useMemo(() => people.filter((p) => `${p.tcKimlik} ${p.adSoyad} ${p.gorev}`.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"))), [people, query]);
  const open = (type, person) => { const current = person.ek2 || {}; const base = type === "kisiselBilgiler" ? Object.fromEntries(personalFields.map(([k]) => [k, ""])) : type === "muayene" ? { muayeneTarihi: "", tansiyonBuyuk: "", tansiyonKucuk: "", nabiz: "", boy: "", kilo: "" } : type === "sonuc" ? { kanaat: [], kisitlamalar: [], aciklama: "" } : type === "tetkikler" ? { items: current.tetkikler || [] } : {}; setDraft({ ...base, ...(current[type] || {}) }); setModal({ type, person }); };
  const save = async () => { if (!modal) return; setSaving(true); try { const data = { ...draft }; if (modal.type === "muayene") nfmFields.forEach(([key]) => { if (!data[key]) data[key] = "NFM"; }); await api(`/firms/${firmId}/persons/${modal.person.tcKimlik}/${modal.type}`, { method: "PUT", body: JSON.stringify({ data }) }); await load(); setModal(null); } catch (error) { alert(error.message); } finally { setSaving(false); } };
  const upload = (person, file) => { if (!file) return; const reader = new FileReader(); reader.onload = () => { setDraft({ items: [...(person.ek2?.tetkikler || []), { name: file.name, dataUrl: reader.result }] }); setModal({ type: "tetkikler", person }); }; reader.readAsDataURL(file); };
  const draw = (event) => { if (!drawing.current || !canvas.current) return; const c = canvas.current; const r = c.getBoundingClientRect(); const ctx = c.getContext("2d"); ctx.lineWidth = 2; ctx.lineCap = "round"; ctx.lineTo((event.clientX-r.left) * c.width / r.width, (event.clientY-r.top) * c.height / r.height); ctx.stroke(); };
  if (!selectedFirm) return <div className="p-6 text-sm text-slate-500">Devam etmek için firma seçiniz.</div>;
  return <main className="min-h-[calc(100vh-150px)] p-3 sm:p-4 md:p-6"><div className="mx-auto max-w-[1600px]"><header className="mb-3 min-h-[56px]"><h1 className="text-xl font-bold text-[#042f4b]">{tetkikler ? "Tetkikler" : "EK-2 Sağlık Muayenesi"}</h1><p className="mt-1 text-sm text-slate-500">{tetkikler ? "Çalışan tetkiklerini yükleyin, görüntüleyin ve indirin." : "Firma çalışanlarının sağlık muayene süreçlerini takip edebilir ve EK-2 formlarını hazırlayabilirsiniz."}</p></header><section className="mb-3 flex items-center gap-4 rounded-md bg-white p-4 shadow-sm"><Building2 className="h-10 w-10 text-blue-600" /><div><b className="text-sm text-[#042f4b]">{selectedFirm.firmaAdi}</b><p className="mt-2 text-xs text-slate-600">Tehlike Sınıfı: <b>{selectedFirm.tehlike || "-"}</b> <span className="ml-5">Çalışan Sayısı: <b>{people.length}</b></span> <span className="ml-5">SGK Sicil No: <b>{selectedFirm.sgkSicilNo || selectedFirm.sgkNo || "-"}</b></span></p></div></section><section className="mb-3 flex gap-2 rounded-md bg-white p-3 shadow-sm"><label className="relative grow"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Personel ara (Ad, Soyad, T.C.)" className="h-9 w-full rounded border border-slate-200 pl-9 pr-3 text-xs" /></label><button onClick={() => setQuery("")} className="h-9 rounded border border-slate-200 px-5 text-xs">Temizle</button></section>{tetkikler ? <TetkikTable rows={rows} upload={upload} open={open} /> : <Ek2Table rows={rows} open={open} />}{!tetkikler && <div className="mt-3 flex justify-end"><BlueButton onClick={() => alert("EK-2 formu kayıtlı muayene verileri üzerinden hazırlanacak.")}>EK-2 Hazırla</BlueButton></div>}</div><Modal isOpen={Boolean(modal)} onClose={() => setModal(null)} title={modal ? `${modal.person.adSoyad} - ${modal.type === "kisiselBilgiler" ? "Kişisel Bilgiler" : modal.type === "saglikBilgileri" ? "Sağlık Bilgileri" : modal.type === "muayene" ? "Fizik Muayene" : modal.type === "sonuc" ? "Kanaat ve Sonuç" : modal.type === "imzalar" ? "İmza ve Fotoğraf" : "Tetkikler"}` : ""} width="max-w-4xl" footer={<><button onClick={() => setModal(null)} className="rounded border px-4 py-2 text-xs">İptal</button><BlueButton onClick={save} disabled={saving}>{saving ? "Kaydediliyor..." : "Kaydet"}</BlueButton></>}>{modal?.type === "kisiselBilgiler" && <PersonalForm person={modal.person} draft={draft} setDraft={setDraft} />}{modal?.type === "saglikBilgileri" && <HealthForm draft={draft} setDraft={setDraft} />}{modal?.type === "muayene" && <ExamForm draft={draft} setDraft={setDraft} />}{modal?.type === "sonuc" && <ResultForm draft={draft} setDraft={setDraft} />}{modal?.type === "tetkikler" && <TetkikList items={draft.items || []} />}{modal?.type === "imzalar" && <SignatureForm draft={draft} setDraft={setDraft} canvas={canvas} drawing={drawing} draw={draw} />}</Modal></main>;
}

function Ek2Table({ rows, open }) { return <section className="overflow-hidden rounded-md bg-white shadow-sm"><div className="max-h-[430px] overflow-auto"><table className="min-w-[1330px] w-full table-fixed text-[11px]"><thead className="bg-slate-50"><tr>{["", "No", "T.C. Kimlik No", "Ad Soyad", "Görev", "Muayene Tarihi", "Kişisel Bilgiler", "Sağlık Bilgileri", "Muayene", "Sonuç", "Geçerlilik", "Dr. İmza", "Personel İmza", "Fotoğraf"].map((x) => <th key={x} className="border-b px-2 py-2 text-center">{x}</th>)}</tr></thead><tbody>{rows.map((p, i) => { const e = p.ek2 || {}; return <tr key={p.tcKimlik} className="border-b"><td className="p-2 text-center"><input type="checkbox" /></td><td className="p-2 text-center">{i + 1}</td><td className="p-2 text-center">{p.tcKimlik}</td><td className="p-2 text-center font-semibold">{p.adSoyad}</td><td className="p-2 text-center">{p.gorev || "-"}</td><td className="p-2 text-center">{e.muayene?.muayeneTarihi || "-"}</td><td><Status ok={Boolean(e.kisiselBilgiler?.dogumYeri)} title="Kişisel bilgiler" onClick={() => open("kisiselBilgiler", p)} /></td><td><Status ok={Boolean(e.saglikBilgileri?.kanGrubu)} title="Sağlık bilgileri" onClick={() => open("saglikBilgileri", p)} /></td><td><Status ok={Boolean(e.muayene?.muayeneTarihi)} title="Fizik muayene" onClick={() => open("muayene", p)} /></td><td><Status ok={Boolean(e.sonuc?.kanaat?.length || e.sonuc?.kanaat)} title="Kanaat ve sonuç" onClick={() => open("sonuc", p)} /></td><td className="p-2 text-center">-</td><td><Status ok={Boolean(e.imzalar?.doktor)} title="Dr. imzası" onClick={() => open("imzalar", p)} /></td><td><Status ok={Boolean(e.imzalar?.personel)} title="Personel imzası" onClick={() => open("imzalar", p)} /></td><td><button className="mx-auto block text-blue-600" onClick={() => open("imzalar", p)}><Image className="h-4 w-4" /></button></td></tr>; })}</tbody></table></div><div className="p-3 text-xs text-slate-600">{rows.length} kayıt gösteriliyor.</div></section>; }
function TetkikTable({ rows, upload, open }) { return <section className="overflow-hidden rounded-md bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-[850px] w-full text-xs"><thead className="bg-slate-50"><tr>{["No", "T.C. Kimlik No", "Ad Soyad", "Görev", "Muayene Tarihi", "İşlemler"].map((x) => <th key={x} className="border-b px-3 py-3 text-center">{x}</th>)}</tr></thead><tbody>{rows.map((p, i) => <tr key={p.tcKimlik} className="border-b"><td className="p-3 text-center">{i + 1}</td><td className="p-3 text-center">{p.tcKimlik}</td><td className="p-3 text-center font-semibold">{p.adSoyad}</td><td className="p-3 text-center">{p.gorev || "-"}</td><td className="p-3 text-center">{p.ek2?.muayene?.muayeneTarihi || "-"}</td><td className="p-3 text-center"><label className="mr-2 cursor-pointer rounded bg-[#2563eb] px-3 py-1.5 font-semibold text-white"><Upload className="mr-1 inline h-3 w-3" />Yükle<input className="sr-only" type="file" onChange={(e) => upload(p, e.target.files?.[0])} /></label><button onClick={() => open("tetkikler", p)} className="mr-2 rounded border px-3 py-1.5"><FileText className="mr-1 inline h-3 w-3" />Görüntüle</button><button onClick={() => open("tetkikler", p)} className="rounded border px-3 py-1.5"><Download className="mr-1 inline h-3 w-3" />İndir</button></td></tr>)}</tbody></table></div><div className="flex justify-end p-3"><button className="rounded bg-emerald-600 px-3 py-1.5 text-xs font-semibold text-white">Belgelere Kaydet</button></div></section>; }
function PersonalForm({ person, draft, setDraft }) { return <div className="grid grid-cols-1 gap-3 md:grid-cols-2">{[["T.C. KİMLİK NO", person.tcKimlik], ["AD SOYAD", person.adSoyad], ["GÖREV", person.gorev]].map(([l, v]) => <Field key={l} label={l} value={v} setValue={() => {}} disabled />)}{personalFields.map(([k, l, o, t]) => <Field key={k} label={l} value={draft[k]} options={o} type={t} setValue={(v) => setDraft({ ...draft, [k]: v })} />)}</div>; }
function HealthForm({ draft, setDraft }) { const choose = (key, label, opts) => <Field label={label} value={draft[key]} options={opts} setValue={(v) => setDraft({ ...draft, [key]: v })} />; return <div className="grid grid-cols-1 gap-3 md:grid-cols-2">{choose("kanGrubu", "KAN GRUBU", healthOptions["KAN GRUBU"])}{choose("kronikHastalik", "KRONİK HASTALIK", healthOptions["KRONİK HASTALIK"])}{choose("tetanoz", "TETANOZ AŞI DURUMU", ["YAPILDI", "YAPILMADI", "BİLİNMİYOR"])}{choose("hepatit", "HEPATİT AŞI DURUMU", ["YAPILDI", "YAPILMADI", "BİLİNMİYOR"])}{choose("digerAsilar", "DİĞER AŞILAR", healthOptions["DİĞER AŞILAR"])}{["GÖRME BOZUKLUĞU", "AMELİYAT", "SİGARA", "ALKOL", ...binaryHealth].map((label) => <HealthChoice key={label} label={label} value={draft[label] || {}} options={healthOptions[label] || ["HAYIR", "EVET"]} onChange={(v) => setDraft({ ...draft, [label]: v })} />)}</div>; }
function HealthChoice({ label, value, options, onChange }) { const choice = up(value.cevap); const details = choice === "DİĞER" || choice === "EVET" || ["SİGARA", "ALKOL"].includes(label) && choice && choice !== "KULLANMIYOR"; return <div className="rounded border border-slate-200 p-2"><label className="block text-xs font-medium">{label}</label><select value={choice} onChange={(e) => onChange({ ...value, cevap: up(e.target.value) })} className="mt-1 h-8 w-full rounded border border-slate-200 bg-white px-2 text-xs"><option value="">SEÇİNİZ</option>{options.map((x) => <option key={x}>{up(x)}</option>)}</select>{details && <input value={value.aciklama || ""} onChange={(e) => onChange({ ...value, aciklama: up(e.target.value) })} placeholder={label === "SİGARA" ? "GÜNLÜK ADET" : label === "ALKOL" ? "SIKLIK / ADET" : "AÇIKLAMA"} className="mt-1 h-8 w-full rounded border border-slate-200 px-2 text-xs uppercase" />}</div>; }
function ExamForm({ draft, setDraft }) { const bmi = draft.boy && draft.kilo ? (Number(draft.kilo) / (Number(draft.boy) / 100) ** 2).toFixed(1) : ""; return <div className="grid grid-cols-1 gap-3 md:grid-cols-2"><Field label="MUAYENE TARİHİ" type="date" value={draft.muayeneTarihi} setValue={(v) => setDraft({ ...draft, muayeneTarihi: v })} />{nfmFields.map(([k, l]) => <Field key={k} label={l} value={draft[k]} setValue={(v) => setDraft({ ...draft, [k]: v })} />)}<Field label="TANSİYON BÜYÜK" type="number" value={draft.tansiyonBuyuk} setValue={(v) => setDraft({ ...draft, tansiyonBuyuk: v })} /><Field label="TANSİYON KÜÇÜK" type="number" value={draft.tansiyonKucuk} setValue={(v) => setDraft({ ...draft, tansiyonKucuk: v })} /><Field label="NABIZ" type="number" value={draft.nabiz} setValue={(v) => setDraft({ ...draft, nabiz: v })} /><Field label="BOY (CM)" type="number" value={draft.boy} setValue={(v) => setDraft({ ...draft, boy: v })} /><Field label="KİLO (KG)" type="number" value={draft.kilo} setValue={(v) => setDraft({ ...draft, kilo: v })} /><Field label="VÜCUT KİTLE İNDEKSİ" value={bmi} setValue={() => {}} disabled /></div>; }
function ResultForm({ draft, setDraft }) { const toggle = (key, v) => setDraft({ ...draft, [key]: (draft[key] || []).includes(v) ? draft[key].filter((x) => x !== v) : [...(draft[key] || []), v] }); const list = (title, key, values) => <div><p className="mb-2 text-xs font-semibold">{title}</p><div className="grid gap-2 md:grid-cols-2">{values.map((v) => <label key={v} className="flex items-center gap-2 rounded border p-2 text-xs"><input type="checkbox" checked={(draft[key] || []).includes(v)} onChange={() => toggle(key, v)} />{v}</label>)}</div></div>; return <div className="space-y-4">{list("KANAAT", "kanaat", opinions)}{list("AÇIKLAMA / KISITLAMA", "kisitlamalar", restrictions)}<Field label="MANUEL AÇIKLAMA" value={draft.aciklama} setValue={(v) => setDraft({ ...draft, aciklama: v })} /></div>; }
function TetkikList({ items }) { return <div className="space-y-2">{items.length ? items.map((x, i) => <div key={`${x.name}-${i}`} className="flex items-center justify-between rounded border p-3 text-sm"><span>{x.name}</span>{x.dataUrl && <a href={x.dataUrl} download={x.name} className="text-blue-600">İndir</a>}</div>) : <p className="text-sm text-slate-500">Henüz tetkik yüklenmedi.</p>}</div>; }
function SignatureForm({ draft, setDraft, canvas, drawing, draw }) { const photo = (e) => { const f = e.target.files?.[0]; if (!f) return; const r = new FileReader(); r.onload = () => setDraft({ ...draft, fotoUrl: r.result }); r.readAsDataURL(f); }; return <div className="space-y-4"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(draft.onay)} onChange={(e) => setDraft({ ...draft, onay: e.target.checked })} />İMZA VE FOTOĞRAF BİLGİSİNİ ONAYLIYORUM.</label><div><p className="mb-2 text-xs font-medium">PERSONEL İMZASI</p><canvas ref={canvas} width="800" height="220" onPointerDown={(e) => { drawing.current = true; const r = e.currentTarget.getBoundingClientRect(); const c = e.currentTarget.getContext("2d"); c.beginPath(); c.moveTo((e.clientX-r.left)*800/r.width, (e.clientY-r.top)*220/r.height); }} onPointerMove={draw} onPointerUp={() => { drawing.current = false; setDraft({ ...draft, personel: canvas.current?.toDataURL("image/png") }); }} className="h-40 w-full touch-none rounded border bg-white" /></div><div className="flex items-center gap-2"><button onClick={() => { const c = canvas.current; c?.getContext("2d").clearRect(0, 0, c.width, c.height); setDraft({ ...draft, personel: "" }); }} className="rounded border px-3 py-2 text-xs">Temizle</button><label className="rounded border px-3 py-2 text-xs"><Camera className="mr-1 inline h-4 w-4" />Fotoğraf seç<input type="file" accept="image/*" className="sr-only" onChange={photo} /></label>{draft.fotoUrl && <img src={draft.fotoUrl} className="h-10 w-10 rounded object-cover" />}</div></div>; }
