import React, { useEffect, useState } from "react";
import { CheckCircle2, ChevronRight, Mail, ShieldCheck } from "lucide-react";
import { API_BASE } from "../config/api";

const API = `${API_BASE.endsWith("/api") ? API_BASE : `${API_BASE}/api`}/mail-integrations`;
const providers = [
  { id: "gmail", name: "Gmail", description: "Google hesabınızla güvenli bağlantı kurun.", color: "bg-red-50 text-red-600" },
  { id: "zoho", name: "Zoho Mail", description: "Zoho hesabınızı belge paylaşımlarına bağlayın.", color: "bg-amber-50 text-amber-700" },
  { id: "microsoft", name: "Microsoft 365", description: "Microsoft hesabınızla bağlantı kurun.", color: "bg-blue-50 text-blue-700" },
];
function headers() { const token = localStorage.getItem("token") || sessionStorage.getItem("token") || localStorage.getItem("authToken") || ""; return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }; }

export default function MailEntegrasyonlari() {
  const [integration, setIntegration] = useState(null);
  const [loading, setLoading] = useState(true); const [connecting, setConnecting] = useState(""); const [error, setError] = useState("");
  async function load() { const response = await fetch(`${API}/me`, { headers: headers() }); const data = await response.json(); setIntegration(data.integration || null); setLoading(false); }
  useEffect(() => { load().catch(() => { setError("Entegrasyon bilgisi alınamadı."); setLoading(false); }); }, []);
  async function connect(provider) { try { setError(""); setConnecting(provider); const response = await fetch(`${API}/oauth/${provider}/start`, { method: "POST", headers: headers() }); const data = await response.json(); if (!response.ok) throw new Error(data.message || "Bağlantı başlatılamadı."); const popup = window.open(data.url, "mailIntegration", "width=560,height=720"); if (!popup) throw new Error("Bağlantı penceresi engellendi. Tarayıcınızdan açılır pencereye izin veriniz."); const timer = window.setInterval(() => { if (popup.closed) { window.clearInterval(timer); setConnecting(""); load().catch(() => null); } }, 700); } catch (e) { setError(e.message); setConnecting(""); } }
  if (loading) return <div className="p-6 text-xs text-slate-500">Entegrasyonlar yükleniyor...</div>;
  return <main className="p-3 text-[#042f4b] sm:p-4 md:p-6"><div className="max-w-5xl"><div className="mb-4"><h1 className="text-lg font-bold sm:text-xl">E-posta Entegrasyonları</h1><p className="mt-1 text-xs text-slate-500">Belge paylaşımında <strong>E-posta ile Gönder</strong> seçildiğinde bağlantı kurduğunuz hesap otomatik gönderici olarak kullanılır.</p></div>{error && <div className="mb-3 rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-xs text-red-700">{error}</div>}{integration && <div className="mb-4 flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-700"><CheckCircle2 size={14}/><span><strong>{integration.email}</strong> hesabı bağlı ve belge paylaşımlarında gönderici olarak kullanılacak.</span></div>}<section className="rounded-lg border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-200 p-4"><h2 className="text-base font-bold">Hesap bağla</h2><p className="mt-1 text-xs text-slate-500">Sağlayıcınızı seçin ve açılan güvenli pencerede hesabınıza izin verin.</p></div><div className="divide-y divide-slate-100">{providers.map((provider) => <button key={provider.id} type="button" onClick={() => connect(provider.id)} disabled={Boolean(connecting)} className="flex w-full items-center gap-3 px-4 py-4 text-left transition hover:bg-slate-50 disabled:opacity-60"><span className={`flex h-9 w-9 items-center justify-center rounded-lg ${provider.color}`}><Mail size={18}/></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{provider.name}</span><span className="mt-0.5 block text-xs text-slate-500">{provider.description}</span></span><span className="inline-flex items-center gap-1 text-xs font-medium text-blue-600">{connecting === provider.id ? "Bağlanıyor..." : "Bağlantı Kur"}<ChevronRight size={15}/></span></button>)}</div></section><p className="mt-3 flex items-start gap-2 text-xs text-slate-500"><ShieldCheck size={14} className="mt-0.5 shrink-0"/>İzin bilgileri şifreli olarak saklanır. İSG Panel e-posta parolanızı görmez veya saklamaz.</p></div></main>;
}
